export const adibData = [
  {
    id: 1,
    name: "Mirmuhsin",
    img: "https://static.zarnews.uz/crop/4/2/736_736_80_42360b91e79b2d5c908b0c1620a06af1.jpg?img=self&v=1620103020",
    life: "05.03.1921 - 2005",
    books: "10",
    eBooks: "5",
    category: "sovet",
    des: `Mirmuhsin (toʻliq ismi Mirmuhsin Mirsaidov, 1921.03.05, Toshkent) — jurnalist, yozuvchi. Oʻzbekiston xalq yozuvchisi (1981). Mirmuhsin Toshkentning Kesakqoʻrgʻon mahallasida kulol oilasida tugʻildi. Eski shahardagi 1-maktabni, Toshkent pedagogika institutining Til va adabiyot fakultetini tugatgan. U Oʻzbekiston yozuvchilari uyushmasida, „Qizil Oʻzbekiston“ gazetasi tahririyatida ishlagan, uzoq muddat „Sharq Yulduzi“, „Mushtum“ va „Guliston“ jurnallarining bosh muharriri boʻlgan.`,
  },
  {
    id: 2,
    name: "Polat Momin",
    img: "https://malumot.ru/wp-content/uploads/2021/03/pocabblat-mocabbmin_60551f1f20a6d.jpeg",
    life: "24.12.1922 - 2004",
    books: "10",
    eBooks: "5",
    category: "sovet",
    des: `Poʻlat Moʻmin (taxallusi; asl ism-sharifi Poʻlat Moʻminov) (1922.24.12 – Toshkent – 2004.2.3) — bolalar shoiri. Oʻzbekiston xalq yozuvchisi (1992). Oʻzbekistonda xizmat koʻrsatgan sanʼat arbobi (1983). Dastlab pedagogika bilim yurtini (1939), soʻng Nizomiy nomidagi Toshkent pedagogika institutini tugatib (1944), oʻqituvchilik bilan shugʻullangan (1944–1947). "Lenin uchquni" gazetasida adabiy xodim (1948–50), Oʻzbekiston davlat nashriyotida boʻlim mudiri (1951–1952), respublika Yozuvchilar uyushmasida adabiy maslahatchi (1954–60), Madaniyat vazirligi qoshidagi Sanʼat ishlari boshqarmasida dramaturgiya boʻyicha bosh muharrir (1962–64).`,
  },
  {
    id: 3,
    name: "Asqad Muxtor ",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuRxtbNj_wKwOHSzluhEBi9mnusArFWDKTdX8J-UW4ziDzAEup_G3_1Q2FuKmVy3bK71c&usqp=CAU",
    life: "23.12.1920 - 1997",
    books: "10",
    eBooks: "5",
    category: "sovet",
    des: `Asqad Muxtor (taxallusi; familiyasi Muxtorov, 1920-yil 23-dekabr, Fargʻona — 1997-yil 17-aprel, Toshkent) — Oʻzbekiston xalq yozuvchisi Asqad Muxtor „Opa-singillar (roman)“, „Tugʻilish“, „Davr mening taqdirimda“, „Chinor“ va „Amu“ romanlari, bir qator qissa, hikoya va dramalari, kuzatuvlarga asoslangan falsafiy lirikasi, jahon adabiyoti namunalaridan badiiy yuksak tarjimalari bilan XX asr oʻzbek adabiyotiga katta hissa qoʻshgan soʻz sanʼatkoridir.`,
  },
  {
    id: 4,
    name: "Oybek",
    img: "https://cdn1.img.sputniknews.uz/img/07e7/0a/14/40170983_26:1:669:494_1920x0_80_0_0_4e8879342fdfd47beb2142e84226e1b8.jpg",
    life: "10.01.1905 - 1968",
    books: "10",
    eBooks: "7",
    category: "sovet",
    des: `Oybek (taxallusi; asl ism-sharifi Musa Toshmuhammad oʻgʻli; 1905.1.10 — Toshkent — 1968.07.1) — shoir, yozuvchi, adabiyotshunos olim va jamoat arbobi. Oʻzbekiston xalq yozuvchisi (1965), Oʻzbekiston Fanlar akademiyasi akademigi (1943). Oybek hunarmand-boʻzchi oilasida tugʻilgan. Dastlab Oqmasjid mahallasidagi eski maktabda (1911-1917), soʻng Munavvarqori Abdurashidxonov tashkil etgan „Namuna“ maktabida (1918-1921) boshlangʻich maʼlumot oladi. Shundan keyin Navoiy nomidagi taʼlim va tarbiya texnikum-internatida tahsil olgach (1921-1925), Toshkent unversitetining ijtimoiy fanlar fakultetida (1925-1927), Leningrad xalq xoʻjaligi institutida (1927-1929) oʻqiydi va ogʻir xastalikka chalingani sababli yana Toshkentga qaytib, Toshkent unversitetida oʻqishni tugatadi (1930).`,
  },
  {
    id: 5,
    name: "Usmon Nosir",
    img: "https://ziyouz.uz/wp-content/uploads/2018/02/madamin-davron.jpg",
    life: "13.11.1912-1944",
    books: "10",
    eBooks: "7",
    category: "sovet",
    des: `1937-yil 13-iyulda shoir „xalq dushmani“ sifatida hibsga olinib, 58-modda bilan sudlanadi va avval Zlatoust qamoqxonasiga, soʻngra Vladivostok va Magadan lagerlariga joylashtiriladi. 1943-yilda Kemerovo viloyatining Mariinskiy tumanidagi lagerga yuboriladi.

        1940-yil 20-avgustda Usmon Nosir Magadan qamoqxonasidan Iosif Stalin nomiga ariza yuboradi va unda u uning „ishini“ qayta koʻrib chiqishni soʻraydi. Bu ariza Iosif Stalin, Lavrentiy Beriya tomonidan koʻrib chiqildi va ular tomonidan maʼqullandi. Oʻzbekiston rahbari Nosirov Usmon „ishini“ qayta koʻrib chiqish toʻgʻrisida buyruq oladi. 1944-yil oxiriga kelib komissiya tuzilib, Usmon Nosir begunoh deb topiladi va reabilitatsiya qilinadi.`,
  },
  {
    id: 6,
    name: "Alisher Navoiy",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFpmgwgfcM3VrdXlAZUodtT1kz1v3PFW9LHyn_chqaPw&s",
    life: "1441–1501",
    books: "56",
    eBooks: "0",
    category: "temuriylar, ",
    des: `Ali-Shir Navoiy, Nizomiddin Ali-Shir Hiraviy nomi bilan ham mashhur oʻzbek shoiri, yozuvchisi, siyosatchisi, tilshunosi, tasavvuf olimi va rassomi. U O‘rta Osiyo tarixidagi eng yirik adabiyot namoyandalaridan biri sanaladi. Navoiy ham fors, ham chag‘atoy turkiy tillarida ijod qilib, chag‘atoy adabiyotining rivojlanishiga katta hissa qo‘shgan. Uning asarlarida adabiyot va tasavvufdan astronomiya va tibbiyotgacha bo‘lgan turli mavzularda she’r, nasr va risolalar mavjud.`,
  },
  {
    id: 7,
    name: "Zahiriddin Muhammad Bobur",
    img: "https://upload.wikimedia.org/wikipedia/commons/1/19/Babur.2.jpg",
    life: "1483–1530",
    books: "50",
    eBooks: "0",
    category: "temuriylar",
    des: `Ali-Shir Navoiy, Nizomiddin Ali-Shir Hiraviy nomi bilan ham mashhur oʻzbek shoiri, yozuvchisi, siyosatchisi, tilshunosi, tasavvuf olimi va rassomi. U O‘rta Osiyo tarixidagi eng yirik adabiyot namoyandalaridan biri sanaladi. Navoiy ham fors, ham chag‘atoy turkiy tillarida ijod qilib, chag‘atoy adabiyotining rivojlanishiga katta hissa qo‘shgan. Uning asarlarida adabiyot va tasavvufdan astronomiya va tibbiyotgacha bo‘lgan turli mavzularda she’r, nasr va risolalar mavjud.`,
  },

  {
    id: 8,
    name: "Abu Ali Ibn Sino",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnxbDZ2lo-riU6uRTil98j0iIioIKj3GxJt2kVMMOaLg&s",
    life: "980–1037",
    books: "36",
    eBooks: "0",
    category: "temuriylar",
    des: `Abu Ali ibn Sino (toʻliq ismi: Abu Ali al-Husayn ibn Abdulloh ibn Sino al-Balxiy; arabcha: أبو علي الحسین بن عبدالله بن سینا) — oʻrta osiyolik qomusiy olim[6], [7] olimi, tabib va faylasuf deb yuritilgan. 980-yilning 18-iyunida Buxoro yaqinidagi Afshona qishlogʻida tugʻilgan va 1037-yilning 16-avgustida Hamadonda vafot etgan. Gʻarbda Avitsenna (ingl. Avicenna) nomi bilan mashhur.`,
  },
  {
    id: 9,
    name: "Abu Rahyon Beruniy",
    img: "https://arboblar.uz/upload/people/a/42222a317a775e40546db8cb9ba7f0380329.jpg",
    life: "973–1048",
    books: "56",
    eBooks: "0",
    category: "temuriylar",
    des: `Beruniy Iroqiylar xonadoniga mansub edi va oʻsha paytda Xorazmdagi hukmron Afrigʻiylarga xayrixoh edi, 995-yil Katni, Xorazmning ikkinchi poytaxti, Gurganj (Urganch)ning amiri Maʼmun ibn Muhammad bosib oladi va Afrigʻiylar sulolasini taxtdan agʻdardi va natijada Beruniy vatanini tashlab Buxoroga ketdi. U yerda u Ibn Sino bilan yozishmalar olib borgan va bu ikki olim oʻrtasida fikr almashilgan.`,
  },
  {
    id: 14,
    name: "Abdulla Qodiriy",
    img: "https://cdn1.img.sputniknews.uz/img/07e6/01/17/22340988_0:0:1301:1300_1920x0_80_0_0_e7093f4e1df0fc85d5b75dc64b3c5875.jpg",
    life: "1894 - 1938",
    books: "20",
    eBooks: "10",
    category: "jadid",
    des: `Abdulla Qodiriy (asosiy taxalluslari: Qodiriy, Julqunboy) (1894.4.10-Toshkent-1938.10.4) – XX a. yangi oʻzbek adabiyotining ulkan namoyandasi, oʻzbek romanchiligining asoschisi; 20-yillardagi muhim ijtimoiy-madaniy jarayonlarning faol ishtirokchisi. Bogʻbon oilasida tugʻilgan. Otasi Qodirbobo (1820—1924) xon, beklar qoʻlida sarbozlik qilgan, rus bosqini paytida (1865) Toshkent mudofaasida qatnashgan. Otasi boshidan oʻtgan sarguzashtlar Abdulla Qodiriyning qator asarlari, xususan tarixiy romanlarining yuzaga kelishida muhim rol oʻynagan. Abdulla Qodiriy musulmon maktabida (1904–1906), rus-tuzem maktabida (1908–12), Abulqosim shayx madrasasida (1916–17) taʼlim oldi; Moskvadagi adabiyot kursida (1925–26) oʻqidi. Yoshligidanoq qadimgi Sharq madaniyati va adabiyoti ruhida tarbiya topgan; arab, fors va rus tillarini oʻrgangan. Jahon adabiyotini ixlos bilan mutolaa qilgan.`,
  },
  {
    id: 15,
    name: "Abdurauf Fitrat ",
    img: "https://api.jadidlar.uz/storage/uploads/jadids/gIuy2g9duuuvOJIUryBynFg2HHu81IZAsdtL5qrK.jpg",
    life: "1885 - 1938",
    books: "40",
    eBooks: "7",
    category: "jadid",
    des: `Abdurauf Fitrat (1886, Buxoro shahri, Buxoro amirligi — 4-oktabr, 1938, Toshkent shahri, Oʻzbekiston SSR) — oʻzbek tarixchisi, filolog, tarjimon, yozuvchi, dramaturg va shoir, zamonaviy oʻzbek tili va adabiyoti asoschilaridan biri, Oʻrta Osiyo jadidchiligining taniqli vakili, birinchi oʻzbek professori (1926)[1]. Jadidchilik milliy maʼrifatparvarlik harakatining tarafdori. Turkiyada taʼlim olgan. Inqilobga qadar Oʻrta Osiyoni Rossiyadan ozod qilinishi harakatlarida faol qatnashgan, politsiya nazorati ostida boʻlgan. Turkiyadagi „Yosh turklar“ harakatidan ilhomlanib, Buxoroda „Yosh buxoroliklar“ partiyasini tuzgan, uning maʼnaviy rahnamosiga aylangan. Doʻsti va maslakdoshi Munzim bilan hamkorlikda buxorolik 70 nafar yosh turkistonliklarni Germaniyaning bir qator oliy taʼlim muassasalariga oʻqishga yuborgan (1922)[2].`,
  },
  {
    id: 16,
    name: "Mahmudxoʻja Behbudiy",
    img: "https://oliymahad.uz/wp-content/uploads/2023/02/720__80_e6d6548f645bf8e61adcafb248f02982.jpg",
    life: "1875 - 1919",
    books: "40",
    eBooks: "15",
    category: "jadid",
    des: `Mahmudxoʻja Behbudiy (Kirill alifbosida: Маҳмудхўжа Беҳбудий; Arab alifbosida: محمود خواجه بهبودی‎; Toʻliq oti - Mahmudxoʻja Behbudiy ibn Behbudxoʻja) (20-Yanvar 1875 Samarqand — 25-Mart 1919 Qarshi) dramaturg, noshir, din va jamoat arbobi, jadidchilik harakati yetakchilaridan biri.

        U Yassaviy avlodidan. 18 yoshidan qozixonada mirzalik qiladi, qozi, mufti darajasiga koʻtariladi. Behbudiy haj safarida boʻlgan chogʻida Arabiston, Misr, Turkiyani kezib chiqqan (1899–1900). Sayohat davomida yangi maktab (usuli jadid) ochish fikri mustahkamlanib bordi. Samarqand yaqinidagi Halvoyi qishlogʻida Ajziy, Rajabaminda Abdulqodir Shakuriylar bilan hamkorlikda yangi maktab ochadi. Behbudiy Qozon va Ufaga borib (1903–1904), u yerdagi yangi usul maktablari bilan tanishadi, tatar ziyolilari bilan aloqani yoʻlga qoʻyadi. Yangi maktablar uchun darsliklar tuzishga kirishadi.f`,
  },
  {
    id: 17,
    name: "Abdulhamid Choʻlpon",
    img: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Abdulhamid_Cholpon.jpg",
    life: "1897 - 1938",
    books: "39",
    eBooks: "24",
    category: "jadid",
    des: `Adabiy ijodi 1913-1914-yillarda Andijonning ijtimoiy va madaniy hayoti haqida xabarlar yozish bilan boshlangan. 1914-yil Toshkentda Munavvar Qori Abdurashidxonov va Ubaydulla Xoʻjayev bilan tanishish Choʻlponning milliy uygʻonish harakati namoyandasi sifatida shakllanishida muhim omil boʻlgan. Choʻlpon „Sadoi Turkiston“ gazetasida dastlabki „Turkistonli qardoshlarimizga“ sheʼri, „Qurboni jaholat“, „Doʻxtir Muhammadyor“ hikoyalari va „Adabiyot nadir?“ maqolasini eʼlon qilib (1914), shu davr adabiyoti namoyandalari safidan oʻrin egallagan. Turkiston aholisining iqtisodiy, ijtimoiy va madaniy qoloqlik sharoitida yashayotganining asosiy sababini Rossiyaning mustamlakachilik siyosatida koʻrgan Choʻlpon boshqa jadidlar qatori, oʻz asarlari bilan xalqning madaniy va maʼrifiy saviyasini koʻtarishga kirishgan.`,
  },
  {
    id: 18,
    name: "Munavvarqori qori",
    img: "https://api.jadidlar.uz/storage/uploads/jadids/YfhwlYNIGiCWzHHpu9CyyjdEpcXtzLASUsGeHGcl.jpg",
    life: "1878 - 1931",
    books: "7",
    eBooks: "3",
    category: "jadid",
    des: `1885-yili Munavvarxon 7 yoshligida otasi Abdurashidxon vafot etadi. Shunda Munavvarxon dastlabki ta’lim-tarbiyani onasi Xosiyatxon otindan oladi. Xat-savodi chiqqach, o‘sha davrda dovrug‘i chiqqan Usmon domladan saboq oldi. Akalari ta’sirida voyaga yeta bordi. Qur’oni karimni xatm qilib, “qori” unvonini olgach, hali ilmga yaxshi kirib bora olmaganini fahmladi. “Yunusxon podsho” madrasasida bir necha yil tahsil ko‘rdi, biroq olgan ilmidan qoniqmadi. 1898-yili Buxoroga borib hadis, fiqh, ilmi tafsir va boshqa sohalar bo‘yicha tahsilni davom ettirdi. Biroq Buxoro madrasalarining imperiya hukumati siyosiy vakilining nazoratida ekanligi va u yerda Munavvarqori orzu qilgan ilmning yo‘qligi ham uni Buxoroni tark etishga majbur qilgan.`,
  },
  {
    id: 19,
    name: "Gʻulom Zafariy",
    img: "https://yuz.uz/imageproxy/1200x/https://yuz.uz/file/news/267c52c8f8990869977a8737353cacc3.jpg",
    life: "1889 — 1938",
    books: "18",
    eBooks: "10",
    category: "jadid",
    des: `Oʼzbek musiqa madaniyati tarixida u musiqiy sahnaviy asarlar muallifi, milliy musiqa namunalari toʼplovchisi hamda tadqiqotchisi sifatida tanilgan. Gʼulom Zafariy va uning safdoshlari (Fitrat, V.Uspenskiy, Elbek) jonbozligi tufayli uyushtirilgan ilk musiqiy-folklor ekspeditsiyalari natijasida musiqa merosini toʼplash va oʼrganish tizimiga asos solindi: 1920-yillar boshida Buxoroda Tanbur chizigʼining nusxasi topildi, 1923—24 yillarda "Buxoro Shashmaqom", 1925 yilda Sh.Shoumarovdan Toshkent-Fargʼona maqom yoʼllari ilk bor notaga yozib olindi. Elbek bilan Fargʼonaga uyushtirilgan ekspeditsiya natijalari asosida milliy musiqiy folklorning birinchi (garchand nota yozuvisiz bajarilgan boʼlsa-da) tizimli nashri — "Аshulalar" toʼplami tayyorlandi[3].`,
  },
  {
    id: 20,
    name: "Isʼhoqxon Toʻra Ibrat",
    img: "https://malumot.ru/wp-content/uploads/2021/02/d0b8d181d2b3d0bed29bd185d0bed0bd-d182d19ed180d0b0-d0b8d0b1d180d0b0d182-1862-1937_601e46ea52881.jpeg",
    life: "1862 - 1937",
    books: "15",
    eBooks: "8",
    category: "jadid",
    des: `Is’hoqxon Ibrat (1862-1937) — maʼrifatparvar shoir, zabardast tilshunos, tarixshunos olim, ilk oʻzbek matbuotchilaridan boʻlib, 1862-yilda Namangan yaqinidagi Toʻraqoʻrgʻon qishlogʻida tugʻilgan. Dastlabki maʼlumotni eski maktabda, soʻngra onasining qoʻlida oladi. Keyinroq Qoʻqonga borib madrasaga oʻqishga kiradi.`,
  },
  {
    id: 21,
    name: "Abdulla Avloniy",
    img: "https://upload.wikimedia.org/wikipedia/commons/9/94/Abdulla_Avloniy.jpg",
    life: "1878 - 1934",
    books: "24",
    eBooks: "18",
    category: "jadid",
    des: `Avloniy 1917-yilda „Turon“ gazetasini nashr qildi. Gazetasida siyosiy va ijtimoiy voqealar yoritilgan. 1918-yilda Avloniy „Ishtirokiyun“ gazetasini tashkil etishda qatnashdi va uning muharriri boʻldi. 1919—1920-yillarda Shoʻro hukumatining Afgʻonistondagi siyosiy vakili[6] va konsuli. Afgʻoniston xalq taʼlimi vaziri[4]. „Kasabachilik harakati“ jurnali bosh muharriri (1921). 1921-yildan Avloniy maktablar ochish, xalqni savodxon qilish, oʻzbek xotin-qizlarini oʻqitish, oʻqituvchilar va ziyoli kadrlar tayyorlash ishlari bilan shugʻullandi. U 1923—1924-yillarda Eski shahardagi xotin-qizlar va erlar maorif bilim yurtlari (inproslar) da mudir, 1924—1929-yillarda Toshkent harbiy maktabida oʻqituvchi, 1930—1934-yillarda Oʻrta Osiyo davlat universiteti (hozirgi Oʻzbekiston Milliy universiteti) da[3] til va adabiyot kafedrasi mudiri, professori.`,
  },
  {
    id: 22,
    name: "Zulfiya Isroilova",
    img: "https://avatars.mds.yandex.net/i?id=0a775e2d7b74c565b34bb89325b5e1fc5191a6a7-9097894-images-thumbs&n=13",
    life: "10.01.1915 – 21.07.1995",
    books: 7,
    eBooks: 3,
    category: "mustaqillik",
    des: `1938—1940-yillarda Yoshlar va oʻsmirlar adabiyoti nashriyotida muharrir, Oʻzbekiston davlat nashriyotida boʻlim mudiri (1941—1950), „Oʻzbekiston xotin-qizlari“ (qarang „Saodat“ jurnali) jurnalida boʻlim mudiri (1950—1953), bosh muharrir (1954—1985) boʻlib ishlagan.`,
  },
  {
    id: 23,
    name: "Hamza Hakimzade Niyazi",
    img: "https://avatars.mds.yandex.net/i?id=e91a538603219a387220469e4fd552131e955ce2-8754774-images-thumbs&n=13",
    life: "03.02.1889 – 20.03.1929",
    books: 12,
    eBooks: 5,
    category: "mustaqillik",
    des: `Niyoziy oʻzbek tilidan tashqari boshqa koʻplab tillarni, jumladan arab, fors, rus va turk tillarini ham bilgan[5][6]. Uning asarlari, odatda, ayollar huquqlari, ijtimoiy tengsizlik va xurofotning tarqalishi kabi ijtimoiy muammolarga bagʻishlangan. Niyoziy Shohimardonda vafot etgan.`,
  },
  {
    id: 24,
    name: "Erkin Vohidov",
    img: "https://avatars.mds.yandex.net/i?id=e4c75bb77b05b8298892260af107d6f5a027a143-10933600-images-thumbs&n=13",
    life: "23.04.1936",
    books: 10,
    eBooks: 8,
    category: "mustaqillik",
    des: `Vohidov 1983-yil Hamza nomidagi Oʻzbekiston SSR Davlat mukofoti bilan taqdirlangan. 1987-yil Oʻzbekiston xalq shoiri unvonini olgan. 1999-yilda esa oliy darajadagi Oʻzbekiston Qahramoni mukofotiga sazovor boʻlgan.`,
  },
  {
    id: 25,
    name: "Gafur Gulam",
    img: "https://avatars.mds.yandex.net/i?id=6e0172ff18df40938ae7134f6a933ce2766ab014-9429884-images-thumbs&n=13",
    life: "10.10.1909 – 12.06.1966",
    books: 8,
    eBooks: 4,
    category: "mustaqillik",
    des: `1923 yil yozilgan „Feliks farzandlari“ sheʼrida yetim bolalar haqida gapirarkan, unda yozuvchi oʻz hayotini ifodalaydi, „Maorif va oʻqituvchi“ oynomasida esa „Goʻzallik qayerda“ nomli ikkinchi sheʼri nashr qilinadi.`,
  },
];
